apiVersion: v1
kind: Pod

metadata:
  name: stress

spec:
  containers:
  - name: stress
    image: veeranki2014/stress:v1
    imagePullPolicy: Always
    command: ["sleep", "200000"]
    resources:
      requests:
        cpu: "150m"
        memory: "200Mi"
      limits:
        cpu: "250m"        
        memory: "500Mi"
