apiVersion: v1
kind: LimitRange

metadata:
  name: my-limit-range

spec:
  limits:
  - default:
      cpu: "250m"
      memory: "500Mi"
    defaultRequest:
      cpu: "150m"
      memory: "250Mi"
    min:
      cpu: "100m"
      memory: "150Mi"
    max:
      cpu: "700m"      
      memory: "750Mi"
    type: Container
...
    limits:
  - default:
      cpu: "250m"
      memory: "500Mi"
    defaultRequest:
      cpu: "150m"
      memory: "250Mi"
    min:
      cpu: "100m"
      memory: "150Mi"
    max:
      cpu: "700m"      
      memory: "750Mi"
    type: Pod

    
