apiVersion: v1
kind: LimitRange

metadata:
  name: my-limit-range

spec:
  limits:
  - default:
      cpu: "250m"
      memory: "500Mi"
    defaultRequest:
      cpu: "150m"
      memory: "250Mi"
    # min:
    #   cpu: "500m"
    #   mem: "500Mi"
    # max:
    #   cpu: "1"      
    #   mem: "1Gi"
    type: Container
    
