apiVersion: v1
kind: Pod

metadata:
  name: nginx
  namespace: roboshop

spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
      - containerPort: 80

  # - name: httpd
  #   image: httpd
  #   ports:
  #     - containerPort: 8080
